engineStrict: true

strictDepBuilds: true
blockExoticSubdeps: true

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false

trustPolicy: no-downgrade
trustLockfile: false

allowBuilds:
  esbuild@0.28.2: true
  "@parcel/watcher@2.6.0": false
  "@swc/core@1.16.2": false
